[build]
  command = """
    python -m pip install --upgrade pip &&
    pip install -r requirements.txt
  """
  publish = "static"
  functions = "netlify/functions"

[build.environment]
  PYTHON_VERSION = "3.9"
  NODE_VERSION = "14"
  FLASK_ENV = "production"
  ZYPHRA_API_KEY = "zsk-a1ba7ed9cbc0a52d5f2b52ad99a1d8a5f786ef186d20862b535caad525b3f6f4"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 