[build]
  command = """
    curl -L https://raw.githubusercontent.com/pyenv/pyenv-installer/master/bin/pyenv-installer | bash &&
    export PATH="$HOME/.pyenv/bin:$PATH" &&
    eval "$(pyenv init -)" &&
    pyenv install 3.9.16 &&
    pyenv global 3.9.16 &&
    python -m pip install --upgrade pip &&
    pip install -r requirements.txt
  """
  publish = "static"
  functions = "netlify/functions"

[build.environment]
  PYTHON_VERSION = "3.9.16"
  NODE_VERSION = "14"
  FLASK_ENV = "production"
  ZYPHRA_API_KEY = "zsk-a1ba7ed9cbc0a52d5f2b52ad99a1d8a5f786ef186d20862b535caad525b3f6f4"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 